django/coolsite/chat/urls.py
from django.urls import path
from .views import ChatView

urlpatterns = [
    path('', ChatView.as_view(), name='chat'),
]

django/coolsite/coolsite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include,re_path
from coolsite import settings
from test_app.views import *
from rest_framework import routers
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView,TokenVerifyView
class MyCustomRouter(routers.SimpleRouter):
    router=[
        routers.Route(url=r'^{prefix}$',
                      mapping={'get':'list'},
                      name='{basename}-list',
                      detail=False,
                      initkwargs={'suffix':'List'}),
        routers.Route(url=r'^{prefix}$',
                      mapping={'get':'retrieve'},
                      name='{basename}-list',
                      detail=True,
                      initkwargs={'suffix':'Detail'}),
        ]
    
router=MyCustomRouter()

urlpatterns = [
    path('', include('test_app.urls')),
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('api/v1/drf-auth/', include('rest_framework.urls')),
    path('chat/', include('chat.urls')),

    path('api/v1/librarylist/', APIList.as_view()),
    path('api/v1/librarylist/<int:pk>/', APIUpdate.as_view()),
    path('api/v1/librarydelete/<int:pk>/', APIDestr.as_view()),
    # path('api/v1/', include(router.urls)), # http://127.0.0.1:8000/api/v1/librarylist/
    
    re_path(r'^api/v1/auth/', include('djoser.urls')),  
    re_path(r'^auth/', include('djoser.urls.authtoken')),
    path('api/v1/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/v1/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/v1/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = PageNotFound 

django/coolsite/test_app/urls.py
# urls.py
from django.urls import path
from .views import *
from django.conf.urls import handler404
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('', main, name='main'),
    path('shop/', shop, name='shop'),
    path('login/', LoginUser.as_view(), name='login_user'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', LogoutUser, name='logout_user'),
    path('python/',  Python.as_view(), name='python'),
    path('post/<slug:post_slug>/', ShowPost.as_view(), name='post'),
    path('post/<slug:post_slug>/delete/', DeletePost.as_view(), name='delete_post'),
    path('category/<slug:cat_slug>/', ShowCategory.as_view(), name='category'),
    path('add_page/', AddPage.as_view(), name='add_page'),
    path('help/', Help.as_view(), name='help'),
    path('search/', SearchView.as_view(), name='search'),
    path('tags/<slug:tag_slug>/', ShowTagPostList.as_view(), name='tag'),
    path('account/settings/', AccountSettingsView.as_view(), name='account_settings'),
    path('react/<int:post_id>/<str:reaction_type>/', react_to_post, name='react_to_post'),
    path("test/",test,name='test')


]

django/coolsite/test_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator

# docker compose exec web python manage.py makemigrations
# docker compose exec web python manage.py migrate


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})

    class Meta:
        verbose_name = 'Категорії'
        verbose_name_plural = "Категорії"



class TagPost(models.Model):
    tag = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(unique=True, db_index=True)

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})


class library(models.Model):
    title = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(max_length=256, unique=True, db_index=True)
    content = models.TextField(blank=True)
    photo = models.ImageField(upload_to="photo/%Y/%M/%d/", null=True, blank=True)
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True, blank=True, db_index=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True,unique=False)

    video_url = models.URLField(max_length=300, null=True, blank=True)
    video_embed_url = models.URLField(max_length=300, null=True, blank=True)
    # lvl_user=models.IntegerField(max_length=1,blank=False,null=False,default=0)
    tags = models.ManyToManyField('TagPost', blank=True, related_name="tags")
    likes = models.IntegerField(default=0)
    dislikes = models.IntegerField(default=0)


    class Meta:
        verbose_name = 'Відома бібліотека'
        verbose_name_plural = 'Відомі бібліотеки'
        ordering = ['time_create', 'time_update']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

    @property
    def video_id(self):

        if self.video_url:
            if 'youtu.be/' in self.video_url:
                return self.video_url.split('/')[-1].split('?')[0]
            elif 'v=' in self.video_url:
                return self.video_url.split('v=')[-1].split('&')[0]
        return None

    def save(self, *args, **kwargs):

        if self.video_id:
            self.video_embed_url = f"https://www.youtube.com/embed/{self.video_id}"
        else:
            self.video_embed_url = None
        super().save(*args, **kwargs)

    def total_likes(self):
        return self.likes

    def total_dislikes(self):
        return self.dislikes


class Reaction(models.Model):
    LIKE = 'L'
    DISLIKE = 'D'
    REACTION_CHOICES = [
        (LIKE, 'Like'),
        (DISLIKE, 'Dislike'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(library, on_delete=models.CASCADE, related_name='reactions')
    reaction = models.CharField(max_length=1, choices=REACTION_CHOICES)

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f"{self.user.username} - {self.reaction} - {self.post.title}"


class Comment(models.Model):
    post = models.ForeignKey('library', on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    unapproved = models.BooleanField(default=False)

    def __str__(self):
        return self.text


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    # 0 - гість/читач, 1 - адмін, 2 - модератор, 3 - автор, ... (приклад)
    lvl_user = models.PositiveSmallIntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(9)]
    )

    class Meta:
        constraints = [
            models.CheckConstraint(check=models.Q(lvl_user__gte=0, lvl_user__lte=9),
                                name="profile_lvl_user_between_0_9")
        ]

    def __str__(self):
        return f"{self.user.username} (lvl {self.lvl_user})"

django/coolsite/test_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from captcha.fields import CaptchaField

from .models import library, TagPost, Comment

class AddPostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=TagPost.objects.all(),
        required=False,
        widget=forms.SelectMultiple(attrs={'id': 'id_tags'})
    )

    class Meta:
        model = library
        fields = ['title', 'slug', 'content', 'photo', 'cat', 'video_url', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'slug': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 30, 'rows': 5}),
        }

    def clean(self):
        cleaned_data = super().clean()
        video_url = cleaned_data.get('video_url')


        return cleaned_data


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логін', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class ContactForm(forms.Form):
    name = forms.CharField(label="Ім'я", max_length=255)
    email = forms.EmailField(label='Email')
    content = forms.CharField(widget=forms.Textarea(attrs={'cols': 60, 'rows': 10}))
    capatcha = CaptchaField()


class SearchForm(forms.Form):
    query = forms.CharField(label='Пошук', max_length=100)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': forms.Textarea(attrs={'cols': 40, 'rows': 5}),
        }


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class CustomPasswordChangeForm(PasswordChangeForm):
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

django/coolsite/test_app/templates/test_app/account_settings.html
{% extends 'test_app/pybase.html' %}
{% load static%}

{% block content %}
<h2>Account Settings</h2>
<link type="text/css" href="{% static 'test_app/css/ttt.css' %}" rel="stylesheet" />

<!-- Profile Update Form -->
<form method="POST" action="">
    {% csrf_token %}
    {{ user_form.as_p }}
    <button type="submit" name="update_profile">Update Profile</button>
</form>

<hr>

<!-- Password Change Form -->
<h2>Change Password</h2>
<form method="POST" action="">
    {% csrf_token %}
    {{ password_form.as_p }}
    <button type="submit" name="change_password">Change Password</button>
</form>
{% endblock %}

django/coolsite/test_app/templates/test_app/addpage.html
{% extends 'test_app/pybase.html' %}
{% block content %}
{% load static%}
<link rel="stylesheet" type="text/css" href="{% static 'test_app/css/addpage.css' %}">

<h1>Добавлення статті</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn-save">Зберегти</button>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        const titleInput = document.querySelector("#id_title");
        const slugInput = document.querySelector("#id_slug");
        let isSlugEdited = false;

        if (titleInput && slugInput) {
            slugInput.addEventListener("input", function () {
                isSlugEdited = true;
            });

            titleInput.addEventListener("input", function () {
                if (!isSlugEdited) {
                    const slug = titleInput.value
                        .toLowerCase()
                        .trim()
                        .replace(/[^a-z0-9\s-]/g, '') 
                        .replace(/\s+/g, '-')
                        .replace(/-+/g, '-');
                    slugInput.value = slug;
                }
            });
        }
    });
</script>

<!-- Підключення бібліотек Select2 -->
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function() {
        $('#id_tags').select2({
            placeholder: 'Виберіть теги',
            allowClear: true,
            closeOnSelect: false
        });
    });
</script>
{% endblock %}

django/coolsite/test_app/templates/test_app/base.html
{% load static %}
<!DOCTYPE html>
<html>
<link rel="shortcut icon" href="{% static 'test_app/images/logs.png' %}" >

<head>
    <link rel="shortcut icon" href="{% static 'test_app/images/logs.png' %}" >
    <title>{{title}}</title>
</head>
<body>
{% block mainmenu %}
{% endblock mainmenu %}

{% block content %}

{% endblock %}

</body>
</html>

django/coolsite/test_app/templates/test_app/help.html
{% extends 'test_app/pybase.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Відпправити</button>
</form>

{% endblock %}

django/coolsite/test_app/templates/test_app/list_categories.html
{% for c in cats %}
{% if c.pk == cat_selected %}
    <li class="selected">{{c.name}}</li>
{% else %}
    <li><a href="{{ c.get_absolute_url }}">{{c.name}}</a></li>
{% endif %}
{% endfor %}

django/coolsite/test_app/templates/test_app/list_tags.html
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{ t.get_absolute_url }}">{{t.tag}}</a></li>
        {% endfor %}
    </ul>

django/coolsite/test_app/templates/test_app/login.html
{% extends 'test_app/pybase.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

<div class="form-error">{{ form.non_field_errors }}</div>

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Війти</button>
</form>

{% endblock %}

django/coolsite/test_app/templates/test_app/main.html
{% extends 'test_app/base.html' %}
{% load static %}
<img src="{% static 'images/logs.png' %}" alt="Наша команда" width="50" height="50">

<head>
    <meta charset="UTF-8">
    <title>{{title}}</title>
</head>

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'test_app/css/main.css' %}">
<header>
    <div class="logo">
        <img src="{% static 'images/logs.png' %}" alt="Наша команда" width="50" height="50">
    </div>
    <nav>
        <ul>
            <li><a href="{% url 'main' %}">Головна</a></li>
            <li><a href="#">Про нас</a></li>
            <li><a href="{% url 'python'  %}">Python</a></li>
            <li><a href="{% url 'shop'  %}">Наш Магазин</a></li>
        </ul>
    </nav>
</header>

<main>
    <section class="about">
        <h2>Про нас</h2>
        <p>Ми - ваша компанія, яка пропонує найкращі продукти та послуги на ринку.</p>
    </section>

    <section class="services">
        <h2>Наші послуги</h2>
        <p>Ми надаємо широкий спектр послуг для вас.</p>
        <ul>
            <section class="services">
                <h2>Наші послуги</h2>
                <ul>


                </ul>
            </section>
            
        </ul>
    </section>  
    
    <section class="team">
        <h2>Наша команда</h2>
        <p>Наша команда складається з професіоналів у своїй галузі.</p>
        <img src="{% static 'test_app/images/team.jpg' %}" alt="Наша команда">
    </section>
</main>

<footer>
    <div class="footer-content">
        <p>&copy; 2024 Мій сайт. Усі права захищені.</p>
        <ul class="social-links">
            <li><a href="#">Facebook</a></li>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Instagram</a></li>
        </ul>
    </div>
</footer>
{% endblock %}

django/coolsite/test_app/templates/test_app/post.html
{% extends 'test_app/pybase.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'test_app/css/post.css' %}">

{% block content %}
<div class="author">
    <i>by: {{ post.author }}</i>
</div>
<h1>{{ post.title }}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{ post.photo.url }}"></p>
{% endif %}

{{ post.content|linebreaks }}

{% if post.video_embed_url %}
<div class="video-container">
    <iframe
        width="560"
        height="315"
        src="{{ post.video_embed_url }}"
        title="YouTube video player"
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen
        loading="lazy">
    </iframe>
</div>
{% endif %}


<div class="tags">
    <h4>Теги:</h4>
    <ul>
        {% for tag in post.tags.all %}
            <li><a href="{{ tag.get_absolute_url }}">{{ tag.tag }}</a></li>
        {% endfor %}
    </ul>
</div>

<div>
    <form action="{% url 'react_to_post' post.id 'L' %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">
            👍  Лайк ({{ post.likes }})
        </button>
    </form>

    <form action="{% url 'react_to_post' post.id 'D' %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">
            👎 Дизлайк ({{ post.dislikes }})
        </button>
    </form>
    {% if user == post.author %}
    <form action="{% url 'delete_post' post_slug=post.slug %}" method="POST" style="display: inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-warning">Видалити пост</button>
    </form>
    {% endif %}
</div>

<h3>Залишити коментар</h3>
{% if user.is_authenticated %}
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Додати коментар</button>
    </form>
{% else %}
    <p>Вам потрібно увійти, щоб залишити коментар.</p>
{% endif %}

<h3>Коментарі</h3>
{% if comments %}
    <div class="comments">
        {% for comment in comments %}
            <div class="comment">
                <p>{{ comment.text }}</p>
                <p><small>by {{ comment.author }} on {{ comment.created_date }}</small></p>
            </div>
        {% endfor %}
    </div>
{% else %}
    <p>Коментарів поки немає.</p>
{% endif %}
{% endblock %}

django/coolsite/test_app/templates/test_app/pybase.html
{% load static %}
{% load test_app_tags %}
<html>
<head>
    <title>{{ title }}</title>
    <link type="text/css" href="{% static 'test_app/css/sr.css' %}" rel="stylesheet" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="{% static 'test_app/images/logs.png' %}" type="image/x-icon"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
    <!--меню -->
{% block mainmenu %}
    <div class="header">
        <ul id="mainmenu" class="mainmenu">
            {% for m in menu %}
                <li><a href="{% url m.url_name %}">{{ m.title }}</a></li>
            {% endfor %}
            <img src="{% static 'test_app/images/logs.png' %}" width="60" height="60">

            {% if request.user.is_authenticated %}
                <li class="last"> <a href="{% url 'account_settings' %}">{{ user.username }}</a> | <a href="{% url 'logout_user' %}">Вийти</a></li>
            {% else %}
                <li class="last"><a href="{% url 'register' %}">Реєстрація</a> | <a href="{% url 'login_user' %}">Війти</a></li>
            {% endif %}
        </ul>
        <div class="clear"></div>
    </div>
{% endblock mainmenu %}

<table class="table-content" border=0 cellpadding="0" cellspacing="0">
    <tr>
        <td valign="top" class="left-chapters">
            <!-- Sidebar -->
            <ul id="leftchapters">
                {% if cat_selected == 0 %}
                    <li class="selected">Всі категорії</li>
                {% else %}
                    <li><a href="{% url 'python' %}">Всі категорії</a></li>
                {% endif %}
                {% show_categories '-name' cat_selected %}
                <li>{% show_tags %}</li>
            </ul>
        </td>
        <!-- Кінець Sidebar'а -->
        <td valign="top" class="content">
            <!-- Блок контента -->
            <div class="content-text">
            {% block content %}
            {% endblock %}
            <!-- Кінець контента -->

            {% if page_obj.has_other_pages %}
            <nav class="list-pages">
                <ul>
            {% if page_obj.has_previous %}
            <li class="page-num">
                <a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
            </li>
            {% endif %}
                    {% for p in paginator.page_range %}
                    {% if page_obj.number == p %}
                    <li class="page-num page-num-selected">{{ p }}</li>
                    {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2 %}
                    <li class="page-num">
                        <a href="?page={{ p }}">{{ p }}</a>
                    </li>
                    {% endif %}
                    {% endfor %}
            {% if page_obj.has_next %}
            <li class="page-num">
                <a href="?page={{ page_obj.next_page_number }}">&gt;</a>
            </li>
            {% endif %}
                </ul>
            </nav>
            {% endif %}
            </div>
            <!-- Кінець -->
        </td>
    </tr>
</table>
</td></tr>
<!-- Footer -->
<tr><td valign=top>
    <div id="footer"></div>
</td></tr></table>
<!-- Кінець footer і сторінки -->
</body>
</html>

django/coolsite/test_app/templates/test_app/register.html
{% extends 'test_app/pybase.html' %}

{% block content %}
<h1>{{title}}</h1>

<form method="post">
    {% csrf_token %}

{% for f in form %}
<p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
<div class="form-error">{{ f.errors }}</div>
{% endfor %}

    <button type="submit">Реєстрація</button>
</form>

{% endblock %}

django/coolsite/test_app/templates/test_app/search_results.html
{% extends 'test_app/pybase.html' %}

{% block content %}
<h1>Результати пошуку</h1>
<form method="get" action="{% url 'search' %}" class="search-form">
    <input type="text" name="q" value="{{ query }}" placeholder="Пошук...">
    <button type="submit">Пошук</button>
</form>

{% if results %}
    <ul>
        {% for result in results %}
            <li><a href="{% url 'post' result.slug %}">{{ result.title }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>Нічого не знайдено.</p>
{% endif %}
{% endblock %}

django/coolsite/test_app/templates/test_app/shop.html
{% load static %}
{% load test_app_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'test_app/css/shop.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block extra_head %}{% endblock %}

</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
<div class="header">
    <div class="logo-container">
        <a href="https://rozetka.com.ua/"> 
			<div class="logo"><img src="{% static 'test_app/images/RozetkaLogo.png' %}" width="200" height="70" alt="rozetka" class="rozetka-image"></div>
        </a>
    </div>
    <div class="search-container">
        <form action="#" method="get">
            <input type="text" placeholder="Я шукаю..." name="q" class="search-input" size="60">
            <button type="submit" class="search-button">Пошук</button>
        </form>
    </div>
</div>
</a></li>
{% for m in menu %}
	{% if not forloop.last %}
			<li><a href="{% url m.url_name %}">{{m.title}}</a></li>
	{% else %}
			<li class="last"><a href="{% url m.url_name %}">{{m.title}}</a></li>
	{% endif %}
{% endfor %}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}

<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!--  -->
	<td valign="top" class="left-chapters">
		<ul id="leftchapters">
			{% for category in categories %}
				<li><a href="{% url 'show_category' cat_id=category.pk %}">{{ category.title }}</a></li>
			{% endfor %}
		</ul>
		
</td>
<!--  -->
<td valign="top" class="content">
	<!--  -->
	{% block breadcrumbs %}
	{% endblock %}

<!--  -->
	<div class="content-text">
{% block content %}
{% endblock %}
	</div>
<!--  -->

</td></tr></table>
</td></tr>
<!-- Footer -->

<!--  -->
</body>
</html>

django/coolsite/test_app/templates/test_app/test.html
{% extends 'test_app/pybase.html' %}